### ISSUE TITLE
Add manual party update

### ISSUE THREAD

**Issue by eayates** [ado21/DynamicMacros#3]
Occasionally the addon will fail to load in the start of the first solo round if queue is joined while in combat. Currently, the addon will not operate at all until the next round. If there was a way to add a command to manually tell the addon to recheck the group (so that you don't have to wait for the actual group update in the next round) or to manually tell the addon to update macros in case the automatic process fails, this would resolve the issue.

**Comment by ado21** [comment]
Does it happen only in such scenarios while player is in combat while pressing Enter Arena ? Since you mentioned word "occasionally" it does not seem like combat issue. Without realizing correct root cause it is hard to look for fix.

However manual trigger is possibility but not best solution

**Comment by Vexali0n** [comment]
To be honest as I am searching through code I see there is small hiccup which prevents addon to trigger in case you are in combat as you mentioned. Originally it was supposed to block addon from triggering while you are in combat inside of arena, but I guess that is useless prevention which is not needed at all.

Since I am not playing these days I could modify addon and send you fixed version for testing purposes.

**Comment by eayates** [comment]
I'd be happy to test it! It is an _outstanding_ addition to the game, very excellent addon. I can pull from a development branch or send you my discord.

**Comment by Vexali0n** [comment]
if you know how to use branches then greatI ll create new one for this issue and please inform me about results

**Comment by Vexali0n** [comment]
Branch name is combat_bug

If this wont help I ll try to implement manual trigger via specific command

**Comment by eayates** [comment]
The bug was uncommon but I will try hard to recreate and let you know, I have the code from the combat branch now! :D

**Comment by Vexali0n** [comment]
Since you did not reply I ll consider this as working
